<!DOCTYPE html>
<html lang="<?php echo $_SESSION['language'] ?? substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2); ?>">
    <head>
        <meta charset="utf-8">
        <title><?php echo $appModel->getLightConfig('name'); ?></title>
        <meta name="description" content="<?php echo $appModel->getLightConfig('description'); ?>" />
        <meta name="keywords" content="<?php echo $appModel->getLightConfig('keywords'); ?>" />
        <meta name="robots" content="index, follow" />
        <link rel="stylesheet" href="/public/css/global.min.css" />
        <?php foreach ($extrasCss as $css) : ?>
            <link rel="stylesheet" href="/public/css/<?php echo $css; ?>.min.css" />
        <?php endforeach; ?>
    </head>

    <body>
        <?php echo $content; ?>
    </body>
</html>